import javax.persistence.*;


@Entity
@Table(name = "my_car")
public class MyCar {


        @Id
        @GeneratedValue(strategy= GenerationType.IDENTITY)
        @Column(name="id")
        int id;

        @Column(name="car_name")
        private String carName;

        @Column(name="power")
        private int power;

        @Column(name="suv")
        private boolean isSUV;

        public MyCar() { }


        //you dont need Id cause its autoGenerated
    public MyCar(String carName, int power, boolean isSUV) {
        this.carName = carName;
        this.power = power;
        this.isSUV = isSUV;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCarName() {
        return carName;
    }

    public void setCarName(String carName) {
        this.carName = carName;
    }

    public int getPower() {
        return power;
    }

    public void setPower(int power) {
        this.power = power;
    }

    public boolean isSUV() {
        return isSUV;
    }

    public void setSUV(boolean SUV) {
        isSUV = SUV;
    }

    @Override
    public String toString() {
        return "MyCar{" +
                "id=" + id +
                ", carName='" + carName + '\'' +
                ", power=" + power +
                ", isSUV=" + isSUV +
                '}';
    }
}
